//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSLib.App.SimpleUpdater {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSLib.App.SimpleUpdater.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 正在请求关闭应用程序... 的本地化字符串。
        /// </summary>
        internal static string ClosingApplications {
            get {
                return ResourceManager.GetString("ClosingApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在计算要下载的文件信息…… 的本地化字符串。
        /// </summary>
        internal static string ComputingFileInfo {
            get {
                return ResourceManager.GetString("ComputingFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在删除原始文件... 的本地化字符串。
        /// </summary>
        internal static string DeleteOriginalFiles {
            get {
                return ResourceManager.GetString("DeleteOriginalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我是用来自动更新的，不要直接拿鼠标戳我嘛 -.- 的本地化字符串。
        /// </summary>
        internal static string DonotRunMeDirectly {
            get {
                return ResourceManager.GetString("DonotRunMeDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载升级包…… 的本地化字符串。
        /// </summary>
        internal static string DownloadPackage {
            get {
                return ResourceManager.GetString("DownloadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载中...{0}/{1} ({2}/{3}) 的本地化字符串。
        /// </summary>
        internal static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前的更新要求最低版本为 {0}，已安装版本为 {1}，请手动更新。 的本地化字符串。
        /// </summary>
        internal static string Ex_VersionTooLow {
            get {
                return ResourceManager.GetString("Ex_VersionTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在执行外部进程..... 的本地化字符串。
        /// </summary>
        internal static string ExecuteExternal {
            get {
                return ResourceManager.GetString("ExecuteExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解压缩升级包…… 的本地化字符串。
        /// </summary>
        internal static string ExtractPackage {
            get {
                return ResourceManager.GetString("ExtractPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装新文件... 的本地化字符串。
        /// </summary>
        internal static string InstallNewFiles {
            get {
                return ResourceManager.GetString("InstallNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装升级包... 的本地化字符串。
        /// </summary>
        internal static string InstallPackages {
            get {
                return ResourceManager.GetString("InstallPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级要求最低版本：{0}
        ///您当前已安装版本：{1}
        ///
        ///您已安装版本过低无法继续运行，请手动下载最新版并重新安装。
        ///软件将会自动退出。 的本地化字符串。
        /// </summary>
        internal static string MinmumVersionRequired_Desc {
            get {
                return ResourceManager.GetString("MinmumVersionRequired_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新已取消 的本地化字符串。
        /// </summary>
        internal static string Update_Cancelled {
            get {
                return ResourceManager.GetString("Update_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败 的本地化字符串。
        /// </summary>
        internal static string Update_Failed {
            get {
                return ResourceManager.GetString("Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预计下载大小：{0} 的本地化字符串。
        /// </summary>
        internal static string UpdateFound_EstimateDownloadSize {
            get {
                return ResourceManager.GetString("UpdateFound_EstimateDownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集未标记为可更新，无法确定更新地址 的本地化字符串。
        /// </summary>
        internal static string Updater_AssemblyNotMarkedAsUpdateable {
            get {
                return ResourceManager.GetString("Updater_AssemblyNotMarkedAsUpdateable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将会自动升级 {0} (版本 {1}) 到 版本 {2}，请等待升级完成。
        ///
        ///如果无法升级，软件将无法使用。 的本地化字符串。
        /// </summary>
        internal static string Updater_AutomaticUpgradeTipForce {
            get {
                return ResourceManager.GetString("Updater_AutomaticUpgradeTipForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将会自动升级 {0} (版本 {1}) 到 版本 {2}，请等待升级完成。 的本地化字符串。
        /// </summary>
        internal static string Updater_AutomaticUpgradeTipNotForce {
            get {
                return ResourceManager.GetString("Updater_AutomaticUpgradeTipNotForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解压缩 {0} 的本地化字符串。
        /// </summary>
        internal static string Updater_ExtractingFile {
            get {
                return ResourceManager.GetString("Updater_ExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装文件 {0} 到 {1} 时发生错误：{2} 的本地化字符串。
        /// </summary>
        internal static string Updater_InstallFileError {
            get {
                return ResourceManager.GetString("Updater_InstallFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法检查更新，错误：{0} 的本地化字符串。
        /// </summary>
        internal static string Updater_UnableToCheckUpdate {
            get {
                return ResourceManager.GetString("Updater_UnableToCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新因为未能关闭正在运行的程序而中止 的本地化字符串。
        /// </summary>
        internal static string Updater_UpdateCanceledByCloseApp {
            get {
                return ResourceManager.GetString("Updater_UpdateCanceledByCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前更新是关键更新，如果不安装此更新，软件将无法继续运行。
        ///
        ///确定要关闭此更新吗？ 的本地化字符串。
        /// </summary>
        internal static string UpdatesFound_CriticalUpdateWarning {
            get {
                return ResourceManager.GetString("UpdatesFound_CriticalUpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 『{1}』已经可以自动更新到 {0} 是否现在就更新？ 的本地化字符串。
        /// </summary>
        internal static string UpdatesFound_Tip {
            get {
                return ResourceManager.GetString("UpdatesFound_Tip", resourceCulture);
            }
        }
    }
}
