//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSLib.App.SimpleUpdater {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSLib.App.SimpleUpdater.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在请求关闭应用程序....
        /// </summary>
        internal static string ClosingApplications {
            get {
                return ResourceManager.GetString("ClosingApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在计算要下载的文件信息…….
        /// </summary>
        internal static string ComputingFileInfo {
            get {
                return ResourceManager.GetString("ComputingFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在删除原始文件....
        /// </summary>
        internal static string DeleteOriginalFiles {
            get {
                return ResourceManager.GetString("DeleteOriginalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我是用来自动更新的，不要直接拿鼠标戳我嘛 -.-.
        /// </summary>
        internal static string DonotRunMeDirectly {
            get {
                return ResourceManager.GetString("DonotRunMeDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载升级包…….
        /// </summary>
        internal static string DownloadPackage {
            get {
                return ResourceManager.GetString("DownloadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载中...{0}/{1} ({2}/{3}).
        /// </summary>
        internal static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在解压缩升级包…….
        /// </summary>
        internal static string ExtractPackage {
            get {
                return ResourceManager.GetString("ExtractPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在安装新文件....
        /// </summary>
        internal static string InstallNewFiles {
            get {
                return ResourceManager.GetString("InstallNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在安装升级包....
        /// </summary>
        internal static string InstallPackages {
            get {
                return ResourceManager.GetString("InstallPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 升级要求最低版本：{0}
        ///您当前已安装版本：{1}
        ///
        ///您已安装版本过低无法继续运行，请手动下载最新版并重新安装。
        ///软件将会自动退出。.
        /// </summary>
        internal static string MinmumVersionRequired_Desc {
            get {
                return ResourceManager.GetString("MinmumVersionRequired_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预计下载大小：{0}.
        /// </summary>
        internal static string UpdateFound_EstimateDownloadSize {
            get {
                return ResourceManager.GetString("UpdateFound_EstimateDownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序集未标记为可更新，无法确定更新地址.
        /// </summary>
        internal static string Updater_AssemblyNotMarkedAsUpdateable {
            get {
                return ResourceManager.GetString("Updater_AssemblyNotMarkedAsUpdateable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将会自动升级 {0} (版本 {1}) 到 版本 {2}，请等待升级完成。
        ///
        ///如果无法升级，软件将无法使用。.
        /// </summary>
        internal static string Updater_AutomaticUpgradeTipForce {
            get {
                return ResourceManager.GetString("Updater_AutomaticUpgradeTipForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将会自动升级 {0} (版本 {1}) 到 版本 {2}，请等待升级完成。.
        /// </summary>
        internal static string Updater_AutomaticUpgradeTipNotForce {
            get {
                return ResourceManager.GetString("Updater_AutomaticUpgradeTipNotForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在解压缩 {0}.
        /// </summary>
        internal static string Updater_ExtractingFile {
            get {
                return ResourceManager.GetString("Updater_ExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装文件 {0} 到 {1} 时发生错误：{2}.
        /// </summary>
        internal static string Updater_InstallFileError {
            get {
                return ResourceManager.GetString("Updater_InstallFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法检查更新，错误：{0}.
        /// </summary>
        internal static string Updater_UnableToCheckUpdate {
            get {
                return ResourceManager.GetString("Updater_UnableToCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动更新因为未能关闭正在运行的程序而中止.
        /// </summary>
        internal static string Updater_UpdateCanceledByCloseApp {
            get {
                return ResourceManager.GetString("Updater_UpdateCanceledByCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前更新是关键更新，如果不安装此更新，软件将无法继续运行。
        ///
        ///确定要关闭此更新吗？.
        /// </summary>
        internal static string UpdatesFound_CriticalUpdateWarning {
            get {
                return ResourceManager.GetString("UpdatesFound_CriticalUpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亲，『{1}』可以升级到 {0} 了喔，现在就动手呗？.
        /// </summary>
        internal static string UpdatesFound_Tip {
            get {
                return ResourceManager.GetString("UpdatesFound_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在执行外部进程......
        /// </summary>
        internal static string ExecuteExternal {
            get {
                return ResourceManager.GetString("ExecuteExternal", resourceCulture);
            }
        }
    }
}
