//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36323
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSLib.App.SimpleUpdater {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSLib.App.SimpleUpdater.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 我是用来自动更新的，不要直接拿鼠标戳我嘛 -.- 的本地化字符串。
        /// </summary>
        internal static string DonotRunMeDirectly {
            get {
                return ResourceManager.GetString("DonotRunMeDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级要求最低版本：{0}
        ///您当前已安装版本：{1} 的本地化字符串。
        /// </summary>
        internal static string MinmumVersionRequired_Desc {
            get {
                return ResourceManager.GetString("MinmumVersionRequired_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预计下载大小：{0} 的本地化字符串。
        /// </summary>
        internal static string UpdateFound_EstimateDownloadSize {
            get {
                return ResourceManager.GetString("UpdateFound_EstimateDownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集未标记为可更新，无法确定更新地址 的本地化字符串。
        /// </summary>
        internal static string Updater_AssemblyNotMarkedAsUpdateable {
            get {
                return ResourceManager.GetString("Updater_AssemblyNotMarkedAsUpdateable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解压缩 {0} 的本地化字符串。
        /// </summary>
        internal static string Updater_ExtractingFile {
            get {
                return ResourceManager.GetString("Updater_ExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装文件 {0} 到 {1} 时发生错误：{2} 的本地化字符串。
        /// </summary>
        internal static string Updater_InstallFileError {
            get {
                return ResourceManager.GetString("Updater_InstallFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法检查更新，错误：{0} 的本地化字符串。
        /// </summary>
        internal static string Updater_UnableToCheckUpdate {
            get {
                return ResourceManager.GetString("Updater_UnableToCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新因为未能关闭正在运行的程序而中止 的本地化字符串。
        /// </summary>
        internal static string Updater_UpdateCanceledByCloseApp {
            get {
                return ResourceManager.GetString("Updater_UpdateCanceledByCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亲，『{1}』可以升级到 {0} 了喔，现在就动手呗？ 的本地化字符串。
        /// </summary>
        internal static string UpdatesFound_Tip {
            get {
                return ResourceManager.GetString("UpdatesFound_Tip", resourceCulture);
            }
        }
    }
}
